# Generated by Django 3.0.3 on 2020-04-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('simbad', models.URLField(null=True, verbose_name='Link to Simbad')),
                ('TNS', models.URLField(null=True, verbose_name='Link to TNS')),
                ('gaia', models.URLField(null=True, verbose_name='Link to Gaia')),
                ('lightcurve', models.ImageField(blank=True, null=True, upload_to='candidates/lightcurves/', verbose_name='Lightcurve')),
                ('image_series', models.ImageField(blank=True, null=True, upload_to='candidates/image_series/', verbose_name='Image series')),
                ('Transient_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vetting.Transient_files')),
            ],
        ),
    ]
